apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-repo-demo
  title: Azure Repository Test
  description: Clone and push to an Azure repository example.
spec:
  owner: iain-b
  type: service

  parameters:
    - title: Fill in some steps
      properties:
        org:
          title: Org name
          type: string
        repo:
          title: Repo name
          type: string 
        project:
          title: Project name
          type: string  

  steps:
    - action: 'publish:azure'
      id: 'publish'
      name: Publish Azure
      input:
        repoUrl: "https://${{ parameters.org }}@dev.azure.com/${{ parameters.org }}/${{ parameters.project }}/_git/${{ parameters.repo }}"
  #   - id: cloneAzureRepo
  #     name: Clone Azure Repo
  #     action: azure:repo:clone
  #     input:
  #       remoteUrl: "https://${{ parameters.org }}@dev.azure.com/${{ parameters.org }}/${{ parameters.project }}/_git/${{ parameters.repo }}"
  #       branch: "main"
  #       targetPath: ./sub-directory

    # - id: pushAzureRepo
    #   name: Push to Remote Azure Repo
    #   action: azure:repo:push
    #   input:
    #     branch: <MY_AZURE_REPOSITORY_BRANCH>
    #     sourcePath: ./sub-directory
    #     gitCommitMessage: Add ${{ parameters.name }} project files

    # - id: pullRequestAzureRepo
    #   name: Create a Pull Request to Azure Repo
    #   action: azure:repo:pr
    #   input:
    #     sourceBranch: <MY_AZURE_REPOSITORY_BRANCH>
    #     targetBranch: "main"
    #     repoId: <MY_AZURE_REPOSITORY>
    #     title: ${{ parameters.name }}
    #     project: <MY_AZURE_PROJECT>
    #     supportsIterations: false

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: "dev.azure.com?owner=<MY_AZURE_PROJECT>&repo=<MY_AZURE_REPOSITORY>&organization=<MY_AZURE_ORGANIZATION>&version=<MY_AZURE_REPOSITORY_BRANCH>"
    #     catalogInfoPath: "/catalog-info.yaml"

  # output:
  #   links:
  #     - title: Repository
  #       url: "dev.azure.com?owner=<MY_AZURE_PROJECT>&repo=<MY_AZURE_REPOSITORY>&organization=<MY_AZURE_ORGANIZATION>"
  #     - title: Open in catalog
  #       icon: catalog
  #       entityRef: ${{ steps.register.output.entityRef }}
