apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ibtest-2
  description: |
    test 2
  annotations:
    github.com/project-slug: roadiehq/sample-service
    datadoghq.com/monitor_tags: iain-local
spec:
  type: service
  owner: user:iain-b
  lifecycle: experimental
