apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ibtest-1
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions and
    Sentry. "Test1"
  annotations:
    github.com/project-slug: roadiehq/sample-service
    # The Sentry organization is stored in the app-config.yaml of the Backstage instance.
    sentry.io/project-slug: sample-service
    backstage.io/techdocs-ref: dir:./
    pagerduty.com/integration-key: 1cf15c07f6f440e0a8d65b7ce80be834
    snyk.io/org-name: dtuite
    snyk.io/project-ids: b6ab231c-a019-4def-a148-4a10a79d6302
    argocd/app-name: ibtest
    aws.com/lambda-function-name: roadie-test-load-to-elastic
    aws.com/lambda-region: eu-west-1
    jira/project-key: IB
    grafana/tag-selector: integrations-ceph
spec:
  type: service
  owner: user:iain-b
  lifecycle: experimental
  implementsApis:
    - sample-service
