apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ibtest-1
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions and
    Sentry.
  tags: ['test', 'test1', 'test2']
  labels:
    test: 'true'
    can.I.have: 'dots'
  annotations:
    github.com/project-slug: roadiehq/sample-service
    # The Sentry organization is stored in the app-config.yaml of the Backstage instance.
    sentry.io/project-slug: sample-service
    backstage.io/techdocs-ref: dir:./
    pagerduty.com/integration-key: 1cf15c07f6f440e0a8d65b7ce80be834
    # snyk.io/org-id: a0e0775e-2b17-4e57-8d85-6c8fbe5bc9a0
    argocd/app-name: ibtest
    aws.com/lambda-function-name: roadie-test-load-to-elastic
    aws.com/lambda-region: eu-west-1
    jira/project-key: WD
    grafana/tag-selector: integrations-ceph
    datadoghq.com/slo_tag: service:iblocal
    datadoghq.com/monitor_tags: service:iblocal
    sonarqube.org/project-key: AcmeInc_blah-template
    # endoflife.date/products: angular,nginx
    endoflife.date/source-location: ./missing.json
spec:
  type: service
  owner: roadie-backstage-admin
  lifecycle: experimental
  implementsApis:
    - sample-service
