apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: test-group-correct
  description: test group
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-alpha@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-alpha@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
