apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: k8s-cluster-iain # need a component to test the k8s plugin, system seems the best fit but needs more thought.
  description: My dev cluster
  backstage.io/kubernetes-label-selector: 'app=backstage'
spec:
  owner: team-a
