site_name: My test docs
repo_url: https://github.com/iain-b/backstage-test-entities/

nav:
  - Home: index.md
  - Test: pointer.md
  - Sub Site: "!include ./sub-site/mkdocs.yml"
plugins:
  - techdocs-core

markdown_extensions:
#  - markdown_inline_mermaid
  - pymdownx.snippets:
      check_paths: true
