site_name: My test docs
repor_url: https://github.com/iain-b/backstage-test-entities/
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Test: pointer.md
  - Sub Site: "!include ./docs/sub-site/mkdocs.yml"
plugins:
  - techdocs-core

markdown_extensions:
#  - markdown_inline_mermaid
  - pymdownx.snippets:
      check_paths: true
