apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monorepo-test
  description: Testing
spec:
  type: github-monorepo
  target: https://github.com/RoadieHQ/sample-split-monorepo?filename=backstage.yaml&filename=catalog-info.yaml
