apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-catalog-register
  title: testing
  description: tesitng catalog:register

spec:
  owner: iain@roadie.io
  type: service
# Edit the template parameters below to see how they will render in the scaffolder form UI
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          enum:
            - Y
            - N
          ui:widget: radio
      dependencies:
        name:
          allOf:
            - if:
                properties:
                  name:
                    const: Y
              then:
                properties:
                  enable_refresh:
                    title: Test
                    type: string
  steps:
    - action: catalog:register
      id: register-with-catalog
      name: Manually register with the catalog
      input:
        catalogInfoUrl: https://github.com/iain-b/backstage-test-entities/blob/main/catalog-info.yaml
