
   
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-catalog-register
  title: testing
  description: tesitng catalog:register

spec:
  owner: iain@roadie.io
  type: service
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - iain-b
  steps:
    - id: publish-repository
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is a test'
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main


    - action: catalog:register
      id: register-with-catalog
      name: Manually register with the catalog
      input:
        repoContentsUrl: ${{ steps.publish-repository.output.repoContentsUrl }}
