apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ibtest-update-jsom
  title: ibtest update json
  description: asdfasdf

spec:
  owner: engineering
  type: example
  parameters:
    - title: Provide some simple information
      required: ['myValue']
      properties:
        myValue:
          title: My Value
          type: string
          description: Value to assign to my-key

  steps:
    - id: fetch
      name: Fetch repo
      action: fetch:plain
      input:
        # Path to the root of the repo of interest. You can also use the RepoUrlPicker to choose one.
        url: ./

    - id: update
      name: Update
      action: roadiehq:utils:json:merge
      input:
        # This file must exist at this path in the repo referenced above
        path: my-file.json
        content:
          test: ${{parameters.myValue}}
#          { 
#            "${{parameters.myValue}}": "${{parameters.myValue}}" 
#          }
          

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=backstage-test-entities&owner=iain-b
        title: Update my-file.json
        description: update description
        branchName: update-my-file-${{ parameters.myValue }}
        targetPath: scaffolder/my-file.json
