apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: workflow-dispatch-example
  title: Workflow example
  description: Tes

spec:
  owner: group:engineering
  type: service
  parameters:
    - title: Choose a location
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - RoadieHQ
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values: {}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is a test'
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        requireCodeOwnerReviews: true
        deleteBranchOnMerge: true

    - id: generateCode
      name: Run workflow
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoURL }}
        workflowId: test.yaml
        branchOrTagName: main
