apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: subcomponent-1
  description: |
    A subcomponent for testing monorepos
  annotations:
    github.com/project-slug: iain-b/backstage-test-entities
    github.com/project-readme-path: components/subcomponent1/README.md
    test: a value
spec:
  type: service
  owner: user:iain-b
  lifecycle: experimental
