apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-user-oauth-1
  title: testing
spec:
  owner: roadie
  type: service

  parameters:
    - title: Input
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - ghes.enginehouse.io
            allowedOwners:
              - ian-link
            allowedRepos:
              - template-test
  steps:
    - id: modify
      name: modify
      action: roadiehq:utils:fs:write
      input:
        path: ./test
        content: testing
    - action: publish:github:pull-request
      id: create-pull-request
      name: Create a pull request
      input:
        repoUrl: 'ghes.enginehouse.io?repo=access-test&owner=ian-link'
        branchName: ibtest-123
        title: 'Make some changes to the files'
        description: 'testing user oauth'
        token: ${{ secrets.USER_OAUTH_TOKEN }}
